[build]
  publish = "."

[[redirects]]
  from = "/randonnees-vtt.html"
  to = "/randonnees.html"
  status = 301

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
